name: Godot Builds
on:
  workflow_call:

jobs:
  godot:
    runs-on: "ubuntu-latest"
    name: Godot Files

    steps:
      - uses: actions/checkout@v4
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: godot_syntax_rust-godot
          path: |
            demo
          if-no-files-found: error
